name: Dólar a Telegram

on:
  schedule:
    - cron: '0 * * * *'   # cada hora
  workflow_dispatch:       # también podés lanzarlo a mano

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Instalar dependencias
        run: pip install requests yfinance pandas numpy
        
      - name: Ejecutar script
        run: python mi_script.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
